### ISSUE TITLE
AssertionError: Table lidarseg not found

### ISSUE THREAD

**Issue by nobody-ai2025** [GangZhang842/CPGNet#3]
非常感谢您优秀的工作！我在复现时遇到如下问题：
Traceback (most recent call last):
  File "F:/phd论文复现/CPGNet-master/train.py", line 196, in <module>
    main(args, config)
  File "F:/phd论文复现/CPGNet-master/train.py", line 137, in main
    train_dataset = eval('datasets.{}.DataloadTrain'.format(pDataset.Train.data_src))(pDataset.Train)
  File "F:\phd论文复现\CPGNet-master\datasets\data.py", line 80, in __init__
    fname_labels = os.path.join(self.nusc.dataroot, self.nusc.get('lidarseg', lidar_sd_token)['filename'])
  File "E:\Anaconda\envs\python37\lib\site-packages\nuscenes\nuscenes.py", line 205, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found
恳请您指教，非常感谢！

**Comment by GangZhang842** [comment]
应该是你的nuscenes数据集没有下载lidarseg的label。没有找到lidarseg的文件夹
